edit_model_name: gpt2-xl
edit_modules: 
- transformer.h.45.mlp.c_proj
- transformer.h.45.mlp.c_fc 
- transformer.h.46.mlp.c_proj 
- transformer.h.46.mlp.c_fc 
- transformer.h.47.mlp.c_proj 
- transformer.h.47.mlp.c_fc 
if_edit_bias: False
init_edit_lr: 1.e-4
edit_lr_lr: 1.e-4
relia_lambda: 0.1
gen_lambda: 0.1
loc_lambda: 1. 
aux_model:
  n_hidden: 1
  hidden_dim: null
  init: id
  norm: True
  act: relu
  rank: 1920
  shared: True
  lr: 1.e-6